title: "<red>Test"
layout:
  - "   "
  - " a "
  - "   "
type: DISPENSER
size: 9
elements:
  'a':
    displayName: "<green>Wow!"
    lore: []
    material: DIAMOND
    amount: 17
    glowing: true
    action: "TEST"