name: LabCommons
version: '${project.version}'
api-version: '1.16'
main: it.mikeslab.commons.LabCommons
description: "Library Plug-in for MikesLab's plug-ins."
website: https://mikeslab.it
author: MikesLab