name: LabCommons
version: 1.0
api-version: '1.14'
main: it.mikeslab.commons.LabCommons
description: "This is not supposed to be a plug-in but a library. If you see this, you are doing something wrong, this plugin.yml is for test purposes."