name: WidenCommons
version: '${project.version}'
main: it.mikeslab.widencommons.WidenCommons
api-version: '1.20'
website: mikeslab.it
author: MikesLab
description: Commons plugin for MikesLab servers, Paper based.

softdepend:
  - PlaceholderAPI

libraries:
  - "com.zaxxer:HikariCP:5.1.0"