name: LabCommons
version: '${project.version}'
main: it.mikeslab.commons.LabCommons
api-version: '1.14'
website: mikeslab.it
author: MikesLab
description: Commons plugin for MikesLab plug-ins

softdepend:
  - PlaceholderAPI

libraries:
  - "com.zaxxer:HikariCP:4.0.3"
  - "org.mongodb:mongodb-driver-sync:5.0.1"