name: WidenCommons
version: '${project.version}'
main: it.mikeslab.commons.MikeCommons
api-version: '1.14'
website: mikeslab.it
author: MikesLab
description: Commons plugin for MikesLab plug-ins

softdepend:
  - PlaceholderAPI

libraries:
  - "com.zaxxer:HikariCP:5.1.0"
  - "org.mongodb:mongodb-driver-sync:5.0.1"