name: LabCommons

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MONGO_TEST_DB: ${{ secrets.MONGO_TEST_DB }}
      MONGO_TEST_DB_PASSWORD: ${{ secrets.MONGO_TEST_DB_PASSWORD }}
      MONGO_TEST_DB_TABLE: ${{ secrets.MONGO_TEST_DB_TABLE }}
      MONGO_TEST_DB_URL: ${{ secrets.MONGO_TEST_DB_URL }}
      SQL_TEST_DB_PASSWORD: ${{ secrets.SQL_TEST_DB_PASSWORD }}
      SQL_TEST_DB_TABLE: ${{ secrets.SQL_TEST_DB_TABLE }}
      SQL_TEST_DB_URL: ${{ secrets.SQL_TEST_DB_URL }}
      SQL_TEST_DB_USER: ${{ secrets.SQL_TEST_DB_USER }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8
      - name: Grant execute permission for mvnw
        run: chmod +x ./mvnw
      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "reposilite-repository",
              "username": "${{ secrets.MAVEN_NAME }}",
              "password": "${{ secrets.MAVEN_SECRET }}"
            }]
      - name: Publish with Maven
        run: ./mvnw -DRunningOnCi=true clean deploy --file pom.xml --batch-mode -P publish-snapshot